name: xsotaHardcore
main: com.xsota.Hardcore
version: 1.0.2
author: xsota
website: https://github.com/xsota/hardcore
commands:
  selfharm:
    description: This is a self harm command.
    usage: /<command>
    permission: xsotaHardcore.basic
    permission-message: You don't have <permission>